baseURL: https://www.zastrow.co
disablePathToLower: true
disableLiveReload: true
languageCode: en-us
title: Philip Zastrow

params:
  description: "Philip Zastrow: Frontend Design Engineer, Web Accessibility Specialist, Writer, Speaker, et al"

Author:
  name: Philip Zastrow
  email: site@zastrow.co

permalinks:
  posts: /:year/:month/:day/:slug/

taxonomies:
  category: categories

rssLimit: 100
timeZone: America/New_York

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  page:
    - HTML
  home:
    - HTML
    - RSS
  section:
    - HTML
  taxonomyTerm:
    - HTML
  taxonomy:
    - HTML

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed
    path: /
