baseURL: https://www.zastrow.co
disablePathToLower: true
disableLiveReload: true
languageCode: en-us
title: Philip Zastrow
Author:
  name: Philip Zastrow
  email: site@zastrow.co

taxonomies:
  category: categories

rssLimit: 50
timeZone: America/New_York

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  page:
    - HTML
  home:
    - HTML
    - RSS
  section:
    - HTML
  taxonomyTerm:
    - HTML
  taxonomy:
    - HTML

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed
    path: /
